<a href="https://colab.research.google.com/github/jrose1022/Data_FoodDeliveryService/blob/main/Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Julierose S. Obias***
*UCOS 3-1*

# **DATA**

In [35]:
import pandas as pd
import numpy as np

np.random.seed(42)

rows = 1000

data = {
    "order_id": np.arange(1, rows+1),
    "customer_id": np.random.randint(1000, 2000, rows),
    "restaurant_name": np.random.choice(["Jollibee", "McDo", "KFC", "Mang Inasal", "Chowking"], rows),
    "food_category": np.random.choice(["Fast Food", "Filipino", "Chinese", "Dessert"], rows),
    "order_date": pd.date_range(start="2026-04-01", periods=rows, freq="H"),
    "delivery_time_minutes": np.random.randint(20, 90, rows),
    "order_status": np.random.choice(["Delivered", "Late", "Cancelled"], rows),
    "payment_method": np.random.choice(["Cash", "GCash", "Card"], rows),
    "order_amount": np.round(np.random.uniform(100, 1000, rows), 2),
    "delivery_fee": np.round(np.random.uniform(20, 100, rows), 2),
    "rider_id": np.random.randint(1, 100, rows),
    "city": np.random.choice(["Manila", "Cavite", "Laguna", "Pasig"], rows)
}

df = pd.DataFrame(data)

df.head()

/tmp/ipykernel_1231/1185437686.py:13: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  "order_date": pd.date_range(start="2026-04-01", periods=rows, freq="H"),

,order_id,customer_id,restaurant_name,food_category,order_date,delivery_time_minutes,order_status,payment_method,order_amount,delivery_fee,rider_id,city
0,1,1102,Chowking,Dessert,2026-04-01 00:00:00,27,Delivered,GCash,990.78,58.58,96,Laguna
1,2,1435,Chowking,Dessert,2026-04-01 01:00:00,83,Late,Card,127.02,24.58,15,Cavite
2,3,1860,Jollibee,Dessert,2026-04-01 02:00:00,29,Late,Card,500.08,33.97,36,Pasig
3,4,1270,Jollibee,Filipino,2026-04-01 03:00:00,57,Late,Cash,554.16,76.59,63,Manila
4,5,1106,McDo,Filipino,2026-04-01 04:00:00,27,Delivered,GCash,205.55,76.94,69,Laguna

# **DATAFRAME FILTERING**

*1. Orders from April 1 to April 4, 2026*

In [36]:
df[(df['order_date'] >= '2026-04-01') & (df['order_date'] <= '2026-04-04')]

,order_id,customer_id,restaurant_name,food_category,order_date,delivery_time_minutes,order_status,payment_method,order_amount,delivery_fee,rider_id,city
0,1,1102,Chowking,Dessert,2026-04-01 00:00:00,27,Delivered,GCash,990.78,58.58,96,Laguna
1,2,1435,Chowking,Dessert,2026-04-01 01:00:00,83,Late,Card,127.02,24.58,15,Cavite
2,3,1860,Jollibee,Dessert,2026-04-01 02:00:00,29,Late,Card,500.08,33.97,36,Pasig
3,4,1270,Jollibee,Filipino,2026-04-01 03:00:00,57,Late,Cash,554.16,76.59,63,Manila
4,5,1106,McDo,Filipino,2026-04-01 04:00:00,27,Delivered,GCash,205.55,76.94,69,Laguna
...,...,...,...,...,...,...,...,...,...,...,...,...
68,69,1013,KFC,Dessert,2026-04-03 20:00:00,75,Late,GCash,534.44,69.34,91,Manila
69,70,1241,McDo,Fast Food,2026-04-03 21:00:00,22,Delivered,Cash,799.71,88.86,16,Laguna
70,71,1776,Mang Inasal,Dessert,2026-04-03 22:00:00,82,Late,GCash,705.56,47.70,90,Manila
71,72,1345,Jollibee,Dessert,2026-04-03 23:00:00,38,Cancelled,Card,751.83,72.30,61,Laguna
72,73,1564,Jollibee,Dessert,2026-04-04 00:00:00,42,Delivered,Card,543.34,48.02,94,Laguna

*2. Late orders only*

In [37]:
df[df['order_status'] == 'Late']

,order_id,customer_id,restaurant_name,food_category,order_date,delivery_time_minutes,order_status,payment_method,order_amount,delivery_fee,rider_id,city
1,2,1435,Chowking,Dessert,2026-04-01 01:00:00,83,Late,Card,127.02,24.58,15,Cavite
2,3,1860,Jollibee,Dessert,2026-04-01 02:00:00,29,Late,Card,500.08,33.97,36,Pasig
3,4,1270,Jollibee,Filipino,2026-04-01 03:00:00,57,Late,Cash,554.16,76.59,63,Manila
8,9,1614,McDo,Chinese,2026-04-01 08:00:00,86,Late,GCash,556.37,29.71,74,Laguna
10,11,1466,KFC,Fast Food,2026-04-01 10:00:00,55,Late,GCash,986.66,34.70,82,Cavite
...,...,...,...,...,...,...,...,...,...,...,...,...
988,989,1593,KFC,Chinese,2026-05-12 04:00:00,21,Late,Cash,935.74,40.85,80,Manila
992,993,1814,Jollibee,Dessert,2026-05-12 08:00:00,44,Late,Cash,726.57,93.40,51,Manila
997,998,1797,Mang Inasal,Fast Food,2026-05-12 13:00:00,43,Late,GCash,191.24,21.27,81,Manila
998,999,1241,KFC,Filipino,2026-05-12 14:00:00,48,Late,GCash,812.70,69.29,58,Laguna
999,1000,1250,KFC,Filipino,2026-05-12 15:00:00,62,Late,Cash,830.41,96.87,54,Laguna

*3. Orders above ₱500*

In [38]:
df[df['order_amount'] > 500]

,order_id,customer_id,restaurant_name,food_category,order_date,delivery_time_minutes,order_status,payment_method,order_amount,delivery_fee,rider_id,city
0,1,1102,Chowking,Dessert,2026-04-01 00:00:00,27,Delivered,GCash,990.78,58.58,96,Laguna
2,3,1860,Jollibee,Dessert,2026-04-01 02:00:00,29,Late,Card,500.08,33.97,36,Pasig
3,4,1270,Jollibee,Filipino,2026-04-01 03:00:00,57,Late,Cash,554.16,76.59,63,Manila
7,8,1020,Chowking,Chinese,2026-04-01 07:00:00,69,Delivered,Card,785.51,29.93,41,Cavite
8,9,1614,McDo,Chinese,2026-04-01 08:00:00,86,Late,GCash,556.37,29.71,74,Laguna
...,...,...,...,...,...,...,...,...,...,...,...,...
992,993,1814,Jollibee,Dessert,2026-05-12 08:00:00,44,Late,Cash,726.57,93.40,51,Manila
995,996,1009,McDo,Filipino,2026-05-12 11:00:00,31,Delivered,Card,579.00,55.80,29,Pasig
996,997,1823,Mang Inasal,Fast Food,2026-05-12 12:00:00,73,Cancelled,Cash,839.48,28.15,37,Cavite
998,999,1241,KFC,Filipino,2026-05-12 14:00:00,48,Late,GCash,812.70,69.29,58,Laguna
999,1000,1250,KFC,Filipino,2026-05-12 15:00:00,62,Late,Cash,830.41,96.87,54,Laguna

*4. Orders paid using GCash*

In [39]:
df[df['payment_method'] == 'GCash']

,order_id,customer_id,restaurant_name,food_category,order_date,delivery_time_minutes,order_status,payment_method,order_amount,delivery_fee,rider_id,city
0,1,1102,Chowking,Dessert,2026-04-01 00:00:00,27,Delivered,GCash,990.78,58.58,96,Laguna
4,5,1106,McDo,Filipino,2026-04-01 04:00:00,27,Delivered,GCash,205.55,76.94,69,Laguna
5,6,1071,Jollibee,Filipino,2026-04-01 05:00:00,44,Cancelled,GCash,252.16,91.87,86,Laguna
6,7,1700,KFC,Filipino,2026-04-01 06:00:00,85,Cancelled,GCash,416.62,66.61,80,Pasig
8,9,1614,McDo,Chinese,2026-04-01 08:00:00,86,Late,GCash,556.37,29.71,74,Laguna
...,...,...,...,...,...,...,...,...,...,...,...,...
990,991,1255,Jollibee,Chinese,2026-05-12 06:00:00,29,Delivered,GCash,375.64,20.05,65,Pasig
991,992,1708,Jollibee,Chinese,2026-05-12 07:00:00,54,Cancelled,GCash,338.57,97.05,75,Manila
994,995,1449,Mang Inasal,Chinese,2026-05-12 10:00:00,36,Delivered,GCash,183.44,26.33,43,Manila
997,998,1797,Mang Inasal,Fast Food,2026-05-12 13:00:00,43,Late,GCash,191.24,21.27,81,Manila
998,999,1241,KFC,Filipino,2026-05-12 14:00:00,48,Late,GCash,812.70,69.29,58,Laguna

*5. Orders in Cavite*

In [40]:
df[df['city'] == 'Cavite']

,order_id,customer_id,restaurant_name,food_category,order_date,delivery_time_minutes,order_status,payment_method,order_amount,delivery_fee,rider_id,city
1,2,1435,Chowking,Dessert,2026-04-01 01:00:00,83,Late,Card,127.02,24.58,15,Cavite
7,8,1020,Chowking,Chinese,2026-04-01 07:00:00,69,Delivered,Card,785.51,29.93,41,Cavite
9,10,1121,Jollibee,Chinese,2026-04-01 09:00:00,68,Cancelled,Card,674.11,77.69,24,Cavite
10,11,1466,KFC,Fast Food,2026-04-01 10:00:00,55,Late,GCash,986.66,34.70,82,Cavite
13,14,1458,Chowking,Filipino,2026-04-01 13:00:00,81,Cancelled,GCash,501.80,21.98,7,Cavite
...,...,...,...,...,...,...,...,...,...,...,...,...
978,979,1723,McDo,Fast Food,2026-05-11 18:00:00,73,Cancelled,GCash,844.91,22.51,95,Cavite
981,982,1751,McDo,Dessert,2026-05-11 21:00:00,63,Late,Card,207.20,94.75,80,Cavite
983,984,1908,McDo,Chinese,2026-05-11 23:00:00,72,Delivered,Card,357.83,78.80,77,Cavite
986,987,1252,KFC,Chinese,2026-05-12 02:00:00,56,Late,Card,852.88,73.54,26,Cavite
996,997,1823,Mang Inasal,Fast Food,2026-05-12 12:00:00,73,Cancelled,Cash,839.48,28.15,37,Cavite

6. Fast food category *only*

In [41]:
df[df['food_category'] == 'Fast Food']

,order_id,customer_id,restaurant_name,food_category,order_date,delivery_time_minutes,order_status,payment_method,order_amount,delivery_fee,rider_id,city
10,11,1466,KFC,Fast Food,2026-04-01 10:00:00,55,Late,GCash,986.66,34.70,82,Cavite
20,21,1661,Mang Inasal,Fast Food,2026-04-01 20:00:00,72,Cancelled,GCash,351.04,40.60,99,Laguna
21,22,1308,Jollibee,Fast Food,2026-04-01 21:00:00,51,Delivered,Cash,216.26,81.95,90,Manila
22,23,1769,Chowking,Fast Food,2026-04-01 22:00:00,35,Delivered,Cash,189.59,50.84,82,Pasig
29,30,1955,McDo,Fast Food,2026-04-02 05:00:00,59,Cancelled,Card,686.88,91.47,25,Pasig
...,...,...,...,...,...,...,...,...,...,...,...,...
977,978,1928,McDo,Fast Food,2026-05-11 17:00:00,68,Cancelled,Cash,346.71,41.30,60,Pasig
978,979,1723,McDo,Fast Food,2026-05-11 18:00:00,73,Cancelled,GCash,844.91,22.51,95,Cavite
980,981,1731,McDo,Fast Food,2026-05-11 20:00:00,72,Delivered,Cash,810.12,69.78,77,Pasig
996,997,1823,Mang Inasal,Fast Food,2026-05-12 12:00:00,73,Cancelled,Cash,839.48,28.15,37,Cavite
997,998,1797,Mang Inasal,Fast Food,2026-05-12 13:00:00,43,Late,GCash,191.24,21.27,81,Manila

*7. Delivery time greater than 60 minutes*

In [42]:
df[df['delivery_time_minutes'] > 60]

,order_id,customer_id,restaurant_name,food_category,order_date,delivery_time_minutes,order_status,payment_method,order_amount,delivery_fee,rider_id,city
1,2,1435,Chowking,Dessert,2026-04-01 01:00:00,83,Late,Card,127.02,24.58,15,Cavite
6,7,1700,KFC,Filipino,2026-04-01 06:00:00,85,Cancelled,GCash,416.62,66.61,80,Pasig
7,8,1020,Chowking,Chinese,2026-04-01 07:00:00,69,Delivered,Card,785.51,29.93,41,Cavite
8,9,1614,McDo,Chinese,2026-04-01 08:00:00,86,Late,GCash,556.37,29.71,74,Laguna
9,10,1121,Jollibee,Chinese,2026-04-01 09:00:00,68,Cancelled,Card,674.11,77.69,24,Cavite
...,...,...,...,...,...,...,...,...,...,...,...,...
982,983,1924,McDo,Filipino,2026-05-11 22:00:00,66,Late,Card,226.49,36.52,24,Pasig
983,984,1908,McDo,Chinese,2026-05-11 23:00:00,72,Delivered,Card,357.83,78.80,77,Cavite
984,985,1557,Mang Inasal,Filipino,2026-05-12 00:00:00,65,Delivered,GCash,566.27,89.32,24,Pasig
996,997,1823,Mang Inasal,Fast Food,2026-05-12 12:00:00,73,Cancelled,Cash,839.48,28.15,37,Cavite
999,1000,1250,KFC,Filipino,2026-05-12 15:00:00,62,Late,Cash,830.41,96.87,54,Laguna

*8. Delivered orders only*

In [43]:
df[df['order_status'] == 'Delivered']

,order_id,customer_id,restaurant_name,food_category,order_date,delivery_time_minutes,order_status,payment_method,order_amount,delivery_fee,rider_id,city
0,1,1102,Chowking,Dessert,2026-04-01 00:00:00,27,Delivered,GCash,990.78,58.58,96,Laguna
4,5,1106,McDo,Filipino,2026-04-01 04:00:00,27,Delivered,GCash,205.55,76.94,69,Laguna
7,8,1020,Chowking,Chinese,2026-04-01 07:00:00,69,Delivered,Card,785.51,29.93,41,Cavite
11,12,1214,KFC,Dessert,2026-04-01 11:00:00,87,Delivered,GCash,791.20,46.27,49,Pasig
16,17,1099,Jollibee,Filipino,2026-04-01 16:00:00,55,Delivered,Card,550.64,42.37,69,Pasig
...,...,...,...,...,...,...,...,...,...,...,...,...
984,985,1557,Mang Inasal,Filipino,2026-05-12 00:00:00,65,Delivered,GCash,566.27,89.32,24,Pasig
989,990,1882,KFC,Chinese,2026-05-12 05:00:00,33,Delivered,Cash,764.87,43.75,38,Pasig
990,991,1255,Jollibee,Chinese,2026-05-12 06:00:00,29,Delivered,GCash,375.64,20.05,65,Pasig
994,995,1449,Mang Inasal,Chinese,2026-05-12 10:00:00,36,Delivered,GCash,183.44,26.33,43,Manila
995,996,1009,McDo,Filipino,2026-05-12 11:00:00,31,Delivered,Card,579.00,55.80,29,Pasig

# **AGGREGATION & GROUPING**

*1. Orders per restaurant*

In [44]:
df.groupby('restaurant_name')['order_id'].count()

restaurant_name
Chowking       204
Jollibee       213
KFC            207
Mang Inasal    173
McDo           203
Name: order_id, dtype: int64

*2. Average delivery time per city*

In [45]:
df.groupby('city')['delivery_time_minutes'].mean()

city
Cavite    53.424710
Laguna    54.944681
Manila    55.330798
Pasig     53.868313
Name: delivery_time_minutes, dtype: float64

*3. Total revenue per restaurant*

In [46]:
df.groupby('restaurant_name')['order_amount'].sum()

restaurant_name
Chowking       109926.59
Jollibee       118888.44
KFC            114959.71
Mang Inasal     93372.20
McDo           107906.90
Name: order_amount, dtype: float64

*4. Average order amount per payment method*

In [47]:
df.groupby('payment_method')['order_amount'].mean()

payment_method
Card     532.093051
Cash     561.877212
GCash    543.075479
Name: order_amount, dtype: float64

*5. Orders per status*

In [48]:
df.groupby('order_status')['order_id'].count()

order_status
Cancelled    329
Delivered    351
Late         320
Name: order_id, dtype: int64

*6. Average delivery fee per city*

In [49]:
df.groupby('city')['delivery_fee'].mean()

city
Cavite    59.003822
Laguna    59.592979
Manila    59.177985
Pasig     57.834403
Name: delivery_fee, dtype: float64

*7. Orders per food category*

In [50]:
df.groupby('food_category')['order_id'].count()

food_category
Chinese      229
Dessert      251
Fast Food    262
Filipino     258
Name: order_id, dtype: int64

*8. Average delivery time per restaurant*

In [51]:
df.groupby('restaurant_name')['delivery_time_minutes'].mean()

restaurant_name
Chowking       56.475490
Jollibee       51.812207
KFC            55.956522
Mang Inasal    53.531792
McDo           54.137931
Name: delivery_time_minutes, dtype: float64